/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bibliotecamunicipal;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class CadastroLeitor extends javax.swing.JFrame {
    ConexaoBanco banco = new ConexaoBanco();
    static boolean alterar = false;
    /**
     * Creates new form CadastroLeitor
     */
    public CadastroLeitor() {
        initComponents();
        banco.conexao();
        banco.executaSQL("SELECT * FROM leitor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtLeitorNome = new javax.swing.JTextField();
        TxtLeitorEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtLeitorCPF = new javax.swing.JFormattedTextField();
        TxtLeitorTelefone = new javax.swing.JFormattedTextField();
        BtnSalvar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        TxtLeitorID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Leitores");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        TxtLeitorNome.setEnabled(false);

        TxtLeitorEndereco.setEnabled(false);
        TxtLeitorEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLeitorEnderecoActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF");

        jLabel4.setText("Telefone");

        try {
            TxtLeitorCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtLeitorCPF.setEnabled(false);

        try {
            TxtLeitorTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtLeitorTelefone.setEnabled(false);

        BtnSalvar.setText("Salvar");
        BtnSalvar.setEnabled(false);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        btnAnterior.setText("<< Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText("Próximo >>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo Leitor");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar Registro");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        TxtLeitorID.setEnabled(false);
        TxtLeitorID.setOpaque(false);
        TxtLeitorID.setPreferredSize(new java.awt.Dimension(1, 1));
        TxtLeitorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLeitorIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtLeitorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLeitorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLeitorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLeitorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtLeitorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TxtLeitorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtLeitorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtLeitorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtLeitorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtLeitorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSalvar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnProximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLeitorEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLeitorEnderecoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtLeitorEnderecoActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        if (alterar == true) {
            try {                
                int id = Integer.parseInt(TxtLeitorID.getText());
                PreparedStatement alteracao = banco.conn.prepareStatement("UPDATE leitor SET nome=?, endereco=?, cpf=?, telefone=? WHERE id=?");
                alteracao.setString(1, TxtLeitorNome.getText());
                alteracao.setString(2, TxtLeitorEndereco.getText());
                alteracao.setString(3, TxtLeitorCPF.getText());
                alteracao.setString(4, TxtLeitorTelefone.getText());
                alteracao.setInt(5, id);
                alteracao.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");

                TxtLeitorNome.setText(null);
                TxtLeitorEndereco.setText(null);
                TxtLeitorCPF.setText(null);
                TxtLeitorTelefone.setText(null);

                banco.executaSQL("SELECT * FROM leitor");

                BtnSalvar.setEnabled(false);
                TxtLeitorNome.setEnabled(false);
                TxtLeitorEndereco.setEnabled(false);
                TxtLeitorCPF.setEnabled(false);
                TxtLeitorTelefone.setEnabled(false);
                btnAnterior.setEnabled(true);
                btnProximo.setEnabled(true);
                
                alterar = false;
            } catch(SQLException ex) {
                Logger.getLogger(CadastroLeitor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar atualizar os dados deste leitor!");
            }
        } else {
            try {
                // TODO add your handling code here:
                PreparedStatement inclusao = banco.conn.prepareStatement("INSERT INTO leitor(nome, endereco, cpf, telefone) VALUES (?,?,?,?)");

                inclusao.setString(1, TxtLeitorNome.getText());
                inclusao.setString(2, TxtLeitorEndereco.getText());
                inclusao.setString(3, TxtLeitorCPF.getText());
                inclusao.setString(4, TxtLeitorTelefone.getText());
                inclusao.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

                TxtLeitorNome.setText(null);
                TxtLeitorEndereco.setText(null);
                TxtLeitorCPF.setText(null);
                TxtLeitorTelefone.setText(null);

                banco.executaSQL("SELECT * FROM leitor");

                BtnSalvar.setEnabled(false);
                TxtLeitorNome.setEnabled(false);
                TxtLeitorEndereco.setEnabled(false);
                TxtLeitorCPF.setEnabled(false);
                TxtLeitorTelefone.setEnabled(false);

            } catch (SQLException ex) {
                Logger.getLogger(CadastroLeitor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar cadastrar este leitor!");
            }
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        try {
            banco.rs.previous();
            TxtLeitorNome.setText(banco.rs.getString("nome"));
            TxtLeitorEndereco.setText(banco.rs.getString("endereco"));
            TxtLeitorCPF.setText(banco.rs.getString("cpf"));
            TxtLeitorTelefone.setText(banco.rs.getString("telefone"));
            TxtLeitorID.setText(banco.rs.getString("id"));
            btnAlterar.setEnabled(true);
            btnProximo.setEnabled(true);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Este é o primeiro registro");
            btnAnterior.setEnabled(false);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            banco.rs.next();
            TxtLeitorNome.setText(banco.rs.getString("nome"));
            TxtLeitorEndereco.setText(banco.rs.getString("endereco"));
            TxtLeitorCPF.setText(banco.rs.getString("cpf"));
            TxtLeitorTelefone.setText(banco.rs.getString("telefone"));
            TxtLeitorID.setText(banco.rs.getString("id"));
            btnAlterar.setEnabled(true);
            btnAnterior.setEnabled(true);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Este é o último registro registro");
            btnProximo.setEnabled(false);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        TxtLeitorNome.setText(null);
        TxtLeitorEndereco.setText(null);
        TxtLeitorCPF.setText(null);
        TxtLeitorTelefone.setText(null);
        
        BtnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnAlterar.setEnabled(false);
        
        TxtLeitorNome.setEnabled(true);
        TxtLeitorEndereco.setEnabled(true);
        TxtLeitorCPF.setEnabled(true);
        TxtLeitorTelefone.setEnabled(true);
        
        TxtLeitorNome.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        alterar = true;
        BtnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(false);
        btnAlterar.setEnabled(false);
        
        TxtLeitorNome.setEnabled(true);
        TxtLeitorEndereco.setEnabled(true);
        TxtLeitorCPF.setEnabled(true);
        TxtLeitorTelefone.setEnabled(true);
        TxtLeitorNome.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void TxtLeitorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLeitorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLeitorIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JFormattedTextField TxtLeitorCPF;
    private javax.swing.JTextField TxtLeitorEndereco;
    private javax.swing.JTextField TxtLeitorID;
    private javax.swing.JTextField TxtLeitorNome;
    private javax.swing.JFormattedTextField TxtLeitorTelefone;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
